apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.index: |
        <h1>Code.education Rocks.</h1>
    nginx.conf: |
        server {
            listen 80;
            index index.html;
            root /usr/share/nginx/html;

            rewrite ^/google$ http://google.com permanent;
        }
